<?php

require_once 'Zend/Mail.php';

/**
 *
 * @category BridgeApp
 * @package App
 * @subpackage Auth
 * @author fieinsaar
 */
class Auth_Model_UiText
{

    const TOKEN_SENT = 1;

    const TOKEN_EMAIL_MESSAGE = 2;

    const TOKEN_NOT_VALID = -1;

    const ACCESS_DENIED = -2;

    /**
     * Send token email
     *
     * @param unknown_type $recipientEmail
     */
    function sendTokenEmail($recipientEmail, $uri)
    {
        $mail = new Zend_Mail('UTF-8');

        $message = $this->getMessage(self::TOKEN_EMAIL_MESSAGE);
        $message = str_replace('%token%', $uri, $message);

        $mail->setBodyText($message)
            ->addTo($recipientEmail)
            ->setSubject($this->getSubjectForMessage(self::TOKEN_EMAIL_MESSAGE))
            ->send();
    }

    /**
     * Get Message by id
     *
     * By default returns empty string
     *
     * @param int $messageId
     * @return string
     */
    function getMessage($messageId)
    {
        switch ($messageId) {
            case self::TOKEN_EMAIL_MESSAGE:
                return <<<MSG
Welcome to Nokia.com InT Content Creation Tool.

In order to access the tools click the link below
or copy/paste it your preferred browser:
%token%

This link is valid for 45 minute access from the computer that was used to
request access. Forwarding this email or the link provided prevents it from
working.

This email was automatically generated by the InT Content Creation Tool platform.

MSG;
            case self::TOKEN_SENT:
                return <<<HTML
<h1>Your access has been approved</h1>
<p>To enter the site, please check your email and click the link in the email
you have just received</p>
HTML;
            case self::ACCESS_DENIED:
                return <<<HTML
<h1>Access to the site has been denied.</h1>
<p>The reasons for this could be one or more of the following:</p>
<ul>
  <li>You or your organization has not been granted access to this tool.</li>
  <li>
    You are attempting to access the site from an IP address that
    has not been granted access to this tool.
  </li>
</ul>
HTML;
            case self::TOKEN_NOT_VALID:
                return <<<HTML
<h1>Access to the site has been denied.</h1>
<p>The reasons for this could be one or more of the following:</p>
<ul>
  <li>
    You or your organization has not been granted access to this tool.
  </li>
  <li>
    You are trying to login with an old token.
  </li>
  <li>
    You are attempting to access the site from an IP address that has
    not been granted access to this tool.
  </li>
</ul>
HTML;
            default:
                return '';
        }
    }

    public function getSubjectForMessage($messageId)
    {
        switch ($messageId) {
            case self::TOKEN_EMAIL_MESSAGE:
                return 'Welcome to the Nokia.com InT Content Creation Tool';
            default:
                return '';
        }
    }
}