<!DOCTYPE html>
<html lang="en">
    <head>
        <?php echo $this->headMeta(); ?>

        <meta http-equiv="X-UA-Compatible" content="IE=9">
        <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
        <link rel="shortcut icon" href="<?php echo $this->baseUrl('/favicon.ico'); ?>" />

        <title>UNICEF - image generator</title>

        <?php
        echo $this->headLink()
            ->appendStylesheet(
                $this->baseUrl('/css/jqueryUi/jqueryUi.css'),
                'screen'
            )
            ->appendStylesheet(
                $this->baseUrl('/css/global.css'),
                    'screen'
            )
        ?>

        <script src="<?php echo $this->baseUrl('/js/dojo/dojo.js'); ?>"
                data-dojo-config="async: true, parseOnLoad: true, cacheBust:'v2'"></script>

        <?php echo $this->headScript()
                ->prependScript("'use strict';\n"); ?>

        <?php echo $this->requireModule('dojo/parser'); ?>

    </head>
    <body class="nokia">
        <header>
            <span class="logo">&nbsp;</span>
            <nav>
                <?php echo $this->navigation()->menu()->renderMenu(
                    null,
                    array('maxDepth' => 1)
                ); ?>
            </nav>
        </header>
        <div class="content-wrapper">
            <?php echo $this->layout()->content; ?>

        </div>
    </body>
</html>